# Generated by Django 3.1.7 on 2021-05-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(blank=True, max_length=100)),
                ('temp', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'adminreg_table',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'c_table',
            },
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'new_table',
            },
        ),
        migrations.CreateModel(
            name='SupplierRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'supplierreg_table',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka')], max_length=100)),
            ],
            options={
                'db_table': 'userorder_table',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userreg_table',
            },
        ),
    ]
