# Generated by Django 3.1.7 on 2021-06-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210523_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tmd_table',
            },
        ),
        migrations.CreateModel(
            name='tud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tud_table',
            },
        ),
    ]
