# Generated by Django 3.1.7 on 2021-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tud_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tud',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Programming', 'Programming'), ('Others', 'Others')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
