# Generated by Django 3.1.7 on 2021-06-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tud_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tud',
            name='Status',
            field=models.CharField(default='In-Progress', max_length=100),
        ),
    ]
