# Generated by Django 3.1.7 on 2021-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userorder_supplierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='UserId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
