# Generated by Django 3.1.7 on 2021-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userorder_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='OrderStatus',
            field=models.CharField(default='In-Progress', max_length=100),
        ),
        migrations.AddField(
            model_name='userorder',
            name='SupplierStatus',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='SupplierId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='UserId',
            field=models.IntegerField(default=-1),
        ),
    ]
